accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from orders.views import get_orders as account_views_order
from .forms import LoginForm

urlpatterns = [
    path('', views.AccountView.as_view(), name="account"),
    path('orders/', account_views_order, name="orders"),
    # path('', views.accountView, name="account"),


    path('register/', views.RegisterView.as_view(), name="register-page"),
    path("login/", views.CustomLoginView.as_view(), name="login-page"),
    path('logout/', auth_views.LogoutView.as_view(template_name="accounts/logout.html"), name="logout-page"),
    
]

cart/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('cart-modal/', views.cart_modal , name="cart-modal"),
    path('add-to-cart/', views.add_to_cart , name="add-to-cart"),
    path('remove-from-cart/', views.remove_from_cart , name="remove-from-cart"),
    path('reset-cart/', views.reset_cart , name="restart-cart"),
    path('update-cart/', views.update_cart, name="update-cart"),

    path('checkout/', views.checkout, name="checkout"),
    path('checkout-1/', views.checkout_summary, name="checkout-1")

    ##path('cart/update', ,name="cart-update"),

]

orders/urls.py
from django.urls import path
from . import views 

urlpatterns = [
    path("confirm-order/", views.confirm_order, name="confirm-order")
]

shop_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings 

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('shop.urls')),
    path('cart/', include('cart.urls')),
    path('account/', include('accounts.urls')),
    path('coupon/', include('coupons.urls')),

    path('orders/', include('orders.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    first_name = models.CharField(max_length=100, null=True)
    last_name = models.CharField(max_length=100, null=True)
    phone_number = models.CharField(max_length=20, null=True)

    def __str__(self):
        return self.user.username
    

class Address(models.Model):
    ADDR_TYPE = [
        (1, 'Home'),
        (2, 'Delivery')
    ]
    postal_code_validator = RegexValidator(
        regex=r'^\d{2}-\d{3}$',
        message = "Postal code must be in format XX-XXX"
    )
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=60, default="Warsaw")
    state = models.CharField(max_length=30, default="Mazowieckie")
    postal_code = models.CharField(max_length=6, validators=[postal_code_validator] ,default="00-000")
    country = models.CharField(max_length=50)
    type = models.IntegerField(choices=ADDR_TYPE, default=1)

    def __str__(self):
        return f'{self.profile} - {self.type}'

orders/models.py
from django.db import models

from accounts.models import Profile
from cart.models import CartItem
# Create your models here.

class Order(models.Model):
    ORD_STATUS =[
        (1, "New"),
        (2, "Waiting for payment"),
        (3, "Paid"),
        (4, "Canceled"),
        (5, "Ended"),
    ]

    PAYMENT_METHod = [
        (1, "BLIK"),
        (2, "PayPal"),
        (3, "Card"),
    ]

    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    items = models.ManyToManyField(CartItem)
    date_ordered = models.DateTimeField(auto_now_add=True)
    sum = models.DecimalField(default=0,decimal_places=2 , max_digits=10)
    status = models.IntegerField(choices=ORD_STATUS, default=1)
    payment = models.IntegerField(choices=PAYMENT_METHod)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm 
from django.contrib.auth.models import User

from accounts.models import Address, Profile

class LoginForm(AuthenticationForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({
            'class': 'form-control',
            'id': 'floatingInput',
            'placeholder': 'login',
        })
        self.fields['password'].widget.attrs.update({
            'class': 'form-control',
            'id': 'floatingInput',
            'placeholder': 'password',
        })

class RegisterForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta(UserCreationForm.Meta):
        model = User
        fields = [
            "username",
            "email",
            "password1",
            "password2",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({
            'class': 'form-control',
            'id': 'floatingInput',
            'placeholder': 'login',
        })
        self.fields['email'].widget.attrs.update({
            'class': 'form-control',
            'id': 'floatingInput',
            'placeholder': 'email',
        })
        self.fields['password1'].widget.attrs.update({
            'class': 'form-control',
            'id': 'floatingInput',
            'placeholder': 'password1',
        })
        self.fields['password2'].widget.attrs.update({
            'class': 'form-control',
            'id': 'floatingInput',
            'placeholder': 'password2',
        })

class UserProfileUpdateForm(forms.ModelForm):
    email = forms.CharField(required=True)
    class Meta:
        model = Profile
        fields = ['first_name', 'last_name', 'phone_number']

    # def clean_email(self):
    #     email = self.cleaned_data.get('email')
    #     if email:
    #         if User.objects.filter(email=email).exclude(username=self.instance.user.username).exists():
    #             raise forms.ValidationError("Podany adres e-mail jest już zajęty.")
    #     return email
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs.update({
            'class': 'form-control',
            'id': 'floatingInput',
            'placeholder': 'text',
        })
        self.fields['last_name'].widget.attrs.update({
            'class': 'form-control',
            'id': 'floatingInput',
            'placeholder': 'text',
        })
        self.fields['email'].widget.attrs.update({
            'class': 'form-control',
            'id': 'floatingInput',
            'placeholder': 'email',
        })
        self.fields['phone_number'].widget.attrs.update({
            'class': 'form-control',
            'id': 'floatingInput',
            'placeholder': 'number',
        })


class HomeAddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = [
            "address",
            "city",
            "state",
            "postal_code",
            "country",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['address'].widget.attrs.update({
            'class': 'form-control',
            'id': 'floatingInput',
            'placeholder': 'text',
        })
        self.fields['city'].widget.attrs.update({
            'class': 'form-control',
            'id': 'floatingInput',
            'placeholder': 'text',
        })
        self.fields['state'].widget.attrs.update({
            'class': 'form-control',
            'id': 'floatingInput',
            'placeholder': 'text',
        })
        self.fields['postal_code'].widget.attrs.update({
            'class': 'form-control',
            'id': 'floatingInput',
            'placeholder': 'number',
        })
        self.fields['country'].widget.attrs.update({
            'class': 'form-control',
            'id': 'floatingInput',
            'placeholder': 'text',
        })

class DeliveryAddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = [
            "address",
            "city",
            "state",
            "postal_code",
            "country",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['address'].widget.attrs.update({
            'class': 'form-control',
            'id': 'floatingInput',
            'placeholder': 'text',
        })
        self.fields['city'].widget.attrs.update({
            'class': 'form-control',
            'id': 'floatingInput',
            'placeholder': 'text',
        })
        self.fields['state'].widget.attrs.update({
            'class': 'form-control',
            'id': 'floatingInput',
            'placeholder': 'text',
        })
        self.fields['postal_code'].widget.attrs.update({
            'class': 'form-control',
            'id': 'floatingInput',
            'placeholder': 'number',
        })
        self.fields['country'].widget.attrs.update({
            'class': 'form-control',
            'id': 'floatingInput',
            'placeholder': 'text',
        })
        
    # username = forms.CharField(max_length=20, required=True)
    # password = forms.CharField(max_length=65, widget=forms.PasswordInput)

    # username.widget.attrs['class'] = "form-control"
    # username.widget.attrs['id'] = "floatingInput"
    # username.widget.attrs['placeholder'] = "login"
    # password.widget.attrs['class'] = "form-control"
    # password.widget.attrs['id'] = "floatingInput"
    # password.widget.attrs['placeholder'] = "password"

accounts/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth import login
from django.http import HttpResponseRedirect, Http404
from django.contrib.auth import login, authenticate
from django.contrib.auth.views import LoginView

from . import forms
from accounts.models import Profile, Address
# Create your views here.

class CustomLoginView(LoginView):
    template_name = "accounts/login.html"
    authentication_form = forms.LoginForm
    next_page = '/'

class LoginView(View):
    def get(self, request):
        form = forms.LoginForm()
        return render(request, 'accounts/login.html', {'form': form})
    

class RegisterView(View):
    def get(self,request):
        form = forms.RegisterForm()

        return render(request, "accounts/register.html", {
            "form": form
        })

    def post(self,request):
        form = forms.RegisterForm(request.POST)
        username = form['username']

        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password2']
            user_login = authenticate(username=username, password=password)
            login(request,user_login)
            
            user_profile = Profile.objects.create(user=request.user)
            user_profile.save()
            
            return HttpResponseRedirect('/')
        else:
            return render(request, "accounts/register.html", {
                "form": form
            })

    
class AccountView(View):
    def get(self, request):
        user_profile = request.user.profile

        # home_address1 = user_profile.address_set.get(type=1)
        home = Address.objects.filter(profile=user_profile, type=1).first()
        home_address = forms.HomeAddressForm(instance=home)

        delivery = Address.objects.filter(profile=user_profile, type=2).first()
        delivery_address = forms.DeliveryAddressForm(instance=delivery)


        initial = {'email': request.user.email}
        user_form = forms.UserProfileUpdateForm(instance=user_profile, initial=initial)

        return render(request, "accounts/account.html", {
            "home_address": home_address,
            "delivery_address": delivery_address,
            "user_form": user_form
        }) 
    
    def post(self, request):
        user_profile = request.user.profile

        home_address = forms.HomeAddressForm(instance=user_profile)
        delivery_address = forms.DeliveryAddressForm(instance=user_profile)

        
        if 'home-address-form' in request.POST:
            home = Address.objects.filter(profile=user_profile, type=1).first()
            form = forms.HomeAddressForm(request.POST, instance=home)

            if form.is_valid():
                address = form.save(commit=False)
                address.profile = user_profile
                address.type = 1
                address.save()
                
                return redirect('account')
            
        if 'delivery-address-form' in request.POST:
            delivery = Address.objects.filter(profile=user_profile, type=2).first()
            form = forms.DeliveryAddressForm(request.POST, instance=delivery)

            if form.is_valid():
                address = form.save(commit=False)
                address.profile = user_profile
                address.type = 2
                address.save()
                
                return redirect('account')

        if 'account-form' in request.POST:
            form = forms.UserProfileUpdateForm(request.POST, instance=user_profile)

            if form.is_valid():
                user = user_profile.user
                user.email = form.cleaned_data['email']
                user.save() ## Saving user email - User
                form.save() ## Saving user data - UserProfile
                return redirect('account')
        else:
            return render(request, "accounts/account.html", {
            "home_address": home_address,
            "delivery_address": delivery_address,
            "user_form": form
            }) 


def accountView(request):
    curr_user = request.user

    context ={
        "curr_user" : curr_user,
    }
    return render(request, "accounts/orders.html",context)






                # if 'checkbox-addres' in request.POST and request.POST['checkbox-addres'] == 'on':
                #     delivery_add = forms.AddressForm(request.POST)

                #     if delivery_add.is_valid():
                #         delivery_add.cleaned_data = form.cleaned_data
                #         delivery_add.type = 2
                #         delivery_add.save()

orders/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_http_methods

# Create your views here.

from orders.models import Order
from cart.models import CartItem, Cart

def get_orders(request):
    curr_user_profile = request.user.profile
    user_orders = Order.objects.filter(user=curr_user_profile)
    print(user_orders)
    context={
        "user_orders":user_orders
    }
    return render(request, "accounts/orders.html", context)

@require_http_methods(["POST"])
def confirm_order(request):
    if request.method == "POST":
        curr_user_profile = request.user.profile

        """
        Add paypal payments
        Add correct status 
        
        """
        cart_items = CartItem.objects.filter(user=request.user)
        cart = Cart.objects.get(user=request.user)
        if not cart_items:
            return redirect('/')
        
        new_order = Order.objects.create(user=curr_user_profile,status=1,payment=2)

        new_order.sum = sum(item.quantity * item.product.price for item in cart.items.all())
        
        new_order.save()

        for cart_item in cart_items:
            new_order.items.add(cart_item)
        cart_items.delete()

        ## clear() on Cart object(attr items), clearing related items, but not deleting them - makes mess
        ## delete() in this way, deleting rows from db 


        return redirect('/')
    else:
        return redirect('/')
    

accounts/templates/accounts/account.html
{% extends "base.html" %}
{% load static %}

{% block page_title %}Account{% endblock  %}

{% block page_css_files %}
<link rel="stylesheet" href="{% static "accounts/css/account.css" %}">

{% endblock  %}

{% block page_content %}


<main class="account">

            <div class="text-center">
                <button class="btn btn-toggle d-md-none collapsed" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-expanded="false">
                    d
                </button>
            </div>
            <div class="container-fluid">
                <div class="row">
                    
                    <div class="col-lg-2 col-md-3 col-sm-6">
                        
                        {% include "accounts/includes/sidebar.html" %}

                    </div>

                    <div class="col-lg-10 col-md-8 col-sm-6">
                        <div class="row ">
                            <div class="col-sm-6 mx-auto accordion" id="accordionAccount">
                                <div class="accordion-item">
                                    <h2 class="accordion-header mb-0 text-center" id="headingOne">
                                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                            Home/Billing Address
                                        </button>
                                    </h2>
                                    <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionAccount">
                                        <div class="card-body p-3">
                                            <form action="{% url "account" %}" method="POST">
                                            {% csrf_token %}
                                            <input name="home-address-form" hidden>
                                            {% for field in home_address %}

                                                <div class="form-outline mb-2 form-floating{% if field.errors %} invalid {% endif %}">
                                                    {{ field }}
                                                    {{ field.label_tag }}
                                                    {{ field.errors }}
                                                </div>

                                            {% endfor %}
                                                <div class="form-check mx-3">
                                                    <input class="form-check-input" type="checkbox" id="flexCheckDefault" name="checkbox-addres">
                                                        <label class="form-check-label" for="flexCheckDefault">Use same to delivery
                                                    </label>
                                                </div>
                                                <div class="text-center">
                                                    <button type="submit" class="btn btn-dark btn-sm">Save</button>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                                <div class="accordion-item mt-1">
                                    <h2 class="accordion-header mb-0 text-center" id="headingTwo">
                                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
                                            Delivery Address
                                        </button>
                                    </h2>
                                    <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionAccount">
                                        <div class="card-body p-3">
                                            <form action="{% url "account" %}" method="POST">
                                            {% csrf_token %}
                                            <input name="delivery-address-form" hidden>
                                            {% for field in delivery_address %}

                                                <div class="form-outline mb-2 form-floating{% if field.errors %} invalid {% endif %}">
                                                    {{ field }}
                                                    {{ field.label_tag }}
                                                    {{ field.errors }}
                                                </div>

                                                {% endfor %}

                                                <div class="text-center">
                                                    <button type="submit" class="btn btn-dark btn-sm">Save</button>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                                    <div class="accordion-item mt-1">
                                        <h2 class="accordion-header mb-0 text-center" id="headingThree">
                                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="true" aria-controls="collapseThree">
                                                Account Details
                                            </button>
                                        </h2>
                                        <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionAccount">
                                            <div class="card-body p-3">
                                                <form action="{% url "account" %}" method="POST">
                                                {% csrf_token %}
                                                <input name="account-form" hidden>
                                                {% for field in user_form %}
                                                    <div class="form-outline mb-2 form-floating{% if field.errors %} invalid {% endif %}">
                                                        {{ field }}
                                                        {{ field.label_tag }}
                                                        {{ field.errors }}
                                                    </div>
                                                    {% endfor %}
                                                    <div class="text-center">
                                                        <button type="submit" class="btn btn-dark btn-sm">Save</button>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
</main>



{% endblock  %}

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load static %}

{% block page_title %}Log in{% endblock %}

{% block page_css_files %}
<link rel="stylesheet" href="{% static "accounts/css/login.css" %}">
<link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/sign-in/">
{% endblock  %}


{% block page_content %}

<body class="text-center">
    <main class="form-signin">
        <form method="POST">
            {% csrf_token %}
            <img class="mb-4" src="{% static "accounts/bootstrap-logo.svg" %}" alt="" width="72" height="57">
            <h1 class="h3 mb-3 fw-normal">Please sign in</h1>

            {{ form.username.error }} 
            
            <div class="form-floating">
                {{form.username}}
                {{form.username.error}}
                <label for="floatingInput">Username</label>
            </div>
            <div class="form-floating">
                {{form.password}}
                {{form.password.error}}
                <label for="floatingInput">Password</label>
            </div> 

            <div class="col">
                <!-- Simple link -->
                <br>
                Don't have account yet? <a class="ml-2" href="{% url 'register-page' %}">Sign In</a>
                <br><br>
                {% comment %} <a href="{% url 'password_reset' %}">Forgot password?</a> {% endcomment %}
            </div>

            <button class="w-100 btn btn-lg btn-primary" type="subdmit">Sign in</button>
            <p class="mt-5 mb-3 text-muted">&copy; 2017–2021</p>
        </form>
    </main>
  </body>


{% endblock  %}

accounts/templates/accounts/logout.html
{% extends "base.html" %}
{% load static %}
{% block page_title %}Logout{% endblock %}

{% block page_css_files %}
<link rel="stylesheet" href="{% static "accounts/css/logout.css" %}">
{% endblock  %}

{% block page_content %}

<div class="container position-absolute top-50 start-50 translate-middle">
    <span>You have been logged out</span>    
    <div class="border-top pt-3">
        <small class="text-muted">
            <a href="{% url 'login-page' %}">Login Again</a>
        </small>
    </div>
</div>

{% endblock %}

accounts/templates/accounts/orders.html
{% extends "base.html" %}
{% load static %}

{% block page_title %}Orders{% endblock  %}

{% block page_css_files %}
<link rel="stylesheet" href="{% static "accounts/css/account.css" %}">

{% endblock  %}


{% block page_content %}
<main class="account">
    <div class="text-center">
        <button class="navbar-toggler position-absodlute d-md-none collapsed bg-black mx-auto mb-3" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
    <div class="container-fluid">
        <div class="row">
            
            <div class="col-lg-1 col-md-3 col-sm-6">
                {% include "accounts/includes/sidebar.html" %}
            </div>

            <div class="col-lg-11 col-md-8 col-sm-6">
                {% if not user_orders %}
                    <p class="fs-2 mt-5 text-center">Make an order! :)</p>
                {% else %}
                    <table class="table table-borderless table-hover align-middle mb-0 bg-white mt-0">
                        <thead class="text-center bg-light">
                        <tr>
                            <th>ID</th>
                            <th>Total</th>
                            <th>Status</th>
                            <th>Date</th>
                            <th>Payment</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody class="text-center">
                            {% for order in user_orders %}
                                <tr class="border-bottom">
                                    <td>
                                        <div class="ms-3">
                                            <p class="fw-bold mb-1">{{order.id}}</p>
                                        </div>
                                    </td>
                                    <td>
                                        <p class="fw-normal mb-1">${{order.sum}}</p>
                                    </td>
                                    <td>
                                        {% if order.status == 1 %}
                                        <span class="badge bg-primary">{{order.get_status_display }}</span>
                                        {% elif order.status == 2 %}
                                        <div>
                                            <span class="badge bg-warning text-dark">{{order.get_status_display }}</span>
                                        </div>
                                        <div>
                                            <span class="badge bg-warning text-dark" >Click to make payment</span>
                                        </div>
                                        {% elif order.status == 3 %}
                                        <span class="badge bg-info text-dark">{{order.get_status_display }}</span>
                                        {% elif order.status == 4 %}
                                        <span class="badge bg-light text-dark">{{order.get_status_display }}</span>
                                        {% elif order.status == 5 %}
                                        <span class="badge bg-success">{{order.get_status_display }}</span>
                                        {% endif %}
                                    </td>
                                    <td>
                                        <p class="text-muted mb-0">{{order.date_ordered | date:"F d o" }}</p>
                                    </td>
                                    <td>
                                        <p class="text-muted mb-0">{{order.get_payment_display }}</p>
                                    </td>
                                    <td>
                                        <p class="text-muted mb-0">X</p>
                                    </td>
                                </tr>
                            {% endfor %}
                    </table>
                  {% endif %}
            </div>
            
        </div>
    </div>
</main>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% load static %}
{% block page_title %}Register{% endblock  %}

{% block page_css_files %}
<link rel="stylesheet" href="{% static "accounts/css/login.css" %}">
{% endblock  %}

{% block page_content %}

<body class="text-center">
  <main class="form-signin">
      <form method="POST">
          {% csrf_token %}
          <img class="mb-4" src="{% static "accounts/bootstrap-logo.svg" %}" alt="" width="72" height="57">
          <h1 class="h3 mb-3 fw-normal">Please sign in</h1>
          
          {% for field in form %}
            <div class="form-floating{% if field.errors %} invalid {% endif %}">
              {{ field }}
              {{ field.label_tag }}
              {{ field.errors }}
            </div>
          {% endfor %}

          <div class="col">
              <!-- Simple link -->
              <br>
              Have account? <a class="ml-2" href="{% url 'login-page' %}">Log In</a>
              <br><br>
              {% comment %} <a href="{% url 'password_reset' %}">Forgot password?</a> {% endcomment %}
          </div>

          <button class="w-100 btn btn-lg btn-primary" type="subdmit">Sign in</button>
          <p class="mt-5 mb-3 text-muted">&copy; 2017–2021</p>
      </form>
  </main>
</body>

{% endblock  %}